### ISSUE TITLE
Other countries?

### ISSUE THREAD

**Issue by madhums** [hungrxyz/Infected#1]
Have you considered adding other countries? Ourworldindata.org is a great data source for that! Curious what you think!

**Comment by markotect** [comment]
@madhums Thanks for the inquiry. 

I did consider other countries, however I only had enough credibility (in Apple's view) to publish numbers for The Netherlands because I live here and my employer is a well known organisation in health care. 

If I had started over I would try to make it world wide but it's too late now, not worth the effort. Next time. 😊
